
const FIREBASE_CONFIG=window.CMA_CONFIG.FIREBASE_CONFIG; const ADMIN_EMAIL=window.CMA_CONFIG.ADMIN_EMAIL;
if(!firebase.apps.length) firebase.initializeApp(FIREBASE_CONFIG);
const CMA_AUTH=firebase.auth();
const CMA_DB=firebase.firestore();
const CMA_PROVIDER=new firebase.auth.GoogleAuthProvider();
CMA_PROVIDER.setCustomParameters({prompt:"select_account"});
CMA_AUTH.setPersistence(firebase.auth.Auth.Persistence.LOCAL).catch(()=>{});
window.CMA={auth:CMA_AUTH,db:CMA_DB,adminEmail:ADMIN_EMAIL};
function normEmail(v){return String(v||"").trim().toLowerCase()}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function showNotice(text){const e=document.getElementById("notice");if(!e)return;e.textContent=text||"";e.style.display=text?"block":"none";if(text)setTimeout(()=>e.style.display="none",4500)}
function redirectToLogin(){const ret=location.pathname.split("/").pop()||"index.html";location.href="index.html?return="+encodeURIComponent(ret)}
async function requireLogin(){if(CMA_AUTH.currentUser)return CMA_AUTH.currentUser;redirectToLogin();return null}
function dateExpired(v){if(!v)return false;const s=typeof v==="string"?v:(v.toDate?v.toDate().toISOString().slice(0,10):"");return !!s && s<new Date().toISOString().slice(0,10)}
async function getAccessState(group){const user=CMA_AUTH.currentUser;if(!user)return {allowed:false,reason:"Please sign in first."};const email=normEmail(user.email);if(email===ADMIN_EMAIL)return {allowed:true,paid:true,admin:true};let settings={freeAccessMode:"fixedPool",freePoolSize:20,freeAttemptLimit:5,siteWideFree:false};try{const ss=await CMA_DB.collection("settings").doc("access").get();if(ss.exists)settings=Object.assign(settings,ss.data()||{})}catch(e){console.warn(e)}if(settings.siteWideFree)return {allowed:true,paid:true,settings};let data={};try{const snap=await CMA_DB.collection("access").doc(email).get();if(snap.exists)data=snap.data()||{}}catch(e){console.warn(e)}if(String(data.status||"active").toLowerCase()==="inactive")return {allowed:false,reason:"Your account is currently inactive.",settings};const groups=Array.isArray(data.groups)?data.groups:[];if(groups.includes(group)&&!dateExpired(data.expiryDate))return {allowed:true,paid:true,settings,data};if(settings.freeAccessMode==="attemptLimit"){let used=0;try{const snap=await CMA_DB.collection("attempts").where("uid","==",user.uid).get();snap.forEach(d=>{if((d.data()||{}).accessType==="free")used++})}catch(e){console.warn(e)}const limit=Math.max(0,Number(settings.freeAttemptLimit)||0);return used<limit?{allowed:true,paid:false,attemptLimit:true,freeUsed:used,freeRemaining:limit-used,settings}:{allowed:false,attemptLimit:true,freeUsed:used,freeRemaining:0,settings,reason:"Your free attempt limit has been reached. Please buy a Premium Plan."}}const limit=Math.max(1,Number(settings.freePoolSize)||20);return {allowed:true,paid:false,fixedPool:true,poolSize:limit,settings}}
async function recordAttempt(group,subject){const user=CMA_AUTH.currentUser;if(!user)return;await CMA_DB.collection("attempts").add({uid:user.uid,email:normEmail(user.email),group,subject,accessType:"free",createdAt:firebase.firestore.FieldValue.serverTimestamp()})}
function logEvent(type,extra={}){const user=CMA_AUTH.currentUser;if(!user)return;CMA_DB.collection("loginEvents").add(Object.assign({uid:user.uid,email:normEmail(user.email),provider:"google",page:location.pathname,eventType:type,loginAt:firebase.firestore.FieldValue.serverTimestamp()},extra)).catch(()=>{})}
function logVisit(){const user=CMA_AUTH.currentUser;if(!user)return;CMA_DB.collection("portalVisits").add({uid:user.uid,email:normEmail(user.email),path:location.pathname,visitAt:firebase.firestore.FieldValue.serverTimestamp()}).catch(()=>{})}
function setupSessionUI(){const email=document.getElementById("sessionEmail"),logout=document.getElementById("logoutBtn"),login=document.getElementById("loginBtn");CMA_AUTH.onAuthStateChanged(user=>{if(email){email.textContent=user?.email||"";email.style.display=user?"inline-block":"none"}if(logout)logout.style.display=user?"inline-block":"none";if(login)login.style.display=user?"none":"inline-block";if(user){logEvent("login");logVisit()}});if(logout)logout.onclick=()=>CMA_AUTH.signOut();if(login)login.onclick=()=>CMA_AUTH.signInWithPopup(CMA_PROVIDER).catch(e=>showNotice(e.message||"Login failed."))}

function ensurePortalUser(u){if(!u)return;CMA_DB.collection("portalUsers").doc(u.uid).set({uid:u.uid,email:normEmail(u.email),name:u.displayName||"",lastSeenAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}).catch(()=>{})}
function waitForAuth(){return new Promise(resolve=>{let done=false;const unsub=CMA_AUTH.onAuthStateChanged(u=>{if(u)ensurePortalUser(u);if(!done){done=true;unsub();resolve(u)}})})}
