/*
FILE: js/home.js
REFERENCE: CMA-ZONE-HOME-V1
PURPOSE: Academic selection and independent attempt/revision countdowns.
EDITABLE AREAS: Academic master, storage key and default attempt.
DEPENDENCIES: index.html, css/home.css, browser localStorage.
IMPORTANT NOTES: V1 stores settings locally; account sync/auth comes later.
LAST UPDATED: 2026-10-04
*/
const ACADEMIC={foundation:{label:"Foundation",groups:{foundation:[["Paper 1","Fundamentals of Business Laws and Business Communication"],["Paper 2","Fundamentals of Financial and Cost Accounting"],["Paper 3","Fundamentals of Business Mathematics and Statistics"],["Paper 4","Fundamentals of Business Economics and Management"]]}},inter:{label:"Intermediate",groups:{g1:[["Paper 5","Business Laws and Ethics"],["Paper 6","Financial Accounting"],["Paper 7","Direct and Indirect Taxation"],["Paper 8","Cost Accounting"]],g2:[["Paper 9","Operations Management and Strategic Management"],["Paper 10","Corporate Accounting and Auditing"],["Paper 11","Financial Management and Business Data Analytics"],["Paper 12","Management Accounting"]]}},final:{label:"Final",groups:{g3:[["Paper 13","Corporate and Economic Laws"],["Paper 14","Strategic Financial Management"],["Paper 15","Direct Tax Laws and International Taxation"]],g4:[["Paper 17","Cost and Management Audit"],["Paper 18","Corporate Financial Reporting"],["Paper 19","Indirect Tax Laws and Practice"]]}}};
const STORE="cma_zone_home_v1",state=JSON.parse(localStorage.getItem(STORE)||"{}"),$=id=>document.getElementById(id),level=$("levelSelect"),group=$("groupSelect"),subjects=$("subjectList");
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function groupOptions(){group.innerHTML='<option value="">Select group</option>';if(!level.value){group.disabled=true;return}const d=ACADEMIC[level.value].groups;Object.keys(d).forEach(k=>{const o=document.createElement("option");o.value=k;o.textContent=k==="g1"?"Group 1":k==="g2"?"Group 2":k==="g3"?"Group 3":k==="g4"?"Group 4":"Foundation";group.appendChild(o)});if(level.value!=="foundation"){const o=document.createElement("option");o.value="both";o.textContent="Both Groups";group.appendChild(o)}group.disabled=false}
function list(){if(!level.value||!group.value)return[];const d=ACADEMIC[level.value].groups;return group.value==="both"?Object.values(d).flat():d[group.value]||[]}
function render(){const items=list();subjects.innerHTML="";if(!items.length){subjects.innerHTML='<div class="empty-state">Select your level and group to see subjects.</div>';return}items.forEach((s,i)=>{const d=document.createElement("div");d.className="subject-card";d.innerHTML='<span class="subject-number">'+String(i+1).padStart(2,"0")+'</span><div><strong>'+s[0]+'</strong><span>'+s[1]+'</span></div>';subjects.appendChild(d)});$("profileStatus").textContent=ACADEMIC[level.value].label+" • "+group.options[group.selectedIndex].text+" selected."}
level.onchange=()=>{groupOptions();render()};group.onchange=()=>{state.level=level.value;state.group=group.value;save();render()};$("saveProfile").onclick=()=>{state.level=level.value;state.group=group.value;save();$("profileStatus").textContent="Selection saved on this device."};
function days(d){if(!d)return null;return Math.max(0,Math.ceil((new Date(d+"T23:59:59")-Date.now())/86400000))}
function tick(){$("attemptCountdown").textContent=(days(state.attemptDate||"2026-12-10")??"—")+" days";$("attemptDateLabel").textContent=(state.attemptName||"December 2026 Attempt")+" • "+(state.attemptDate||"2026-12-10");const r=days(state.revisionDate);$("revisionCountdown").textContent=r===null?"—":r+" days"}
$("editAttempt").onclick=()=>{$("attemptEditor").classList.toggle("hidden")};$("saveAttempt").onclick=()=>{state.attemptName=$("attemptName").value.trim()||"Attempt";state.attemptDate=$("attemptDate").value;save();$("attemptEditor").classList.add("hidden");tick()};
$("editRevision").onclick=()=>{$("revisionEditor").classList.toggle("hidden");$("revisionEmpty").classList.add("hidden")};$("saveRevision").onclick=()=>{state.revisionName=$("revisionNameInput").value.trim()||"Revision";state.revisionDate=$("revisionDate").value;save();$("revisionName").textContent=state.revisionName;$("revisionDateLabel").textContent=state.revisionDate;$("revisionEmpty").classList.add("hidden");$("revisionEditor").classList.add("hidden");$("revisionView").classList.remove("hidden");tick()};
if(state.level){level.value=state.level;groupOptions();group.value=state.group||"";render()}if(state.attemptName)$("attemptName").value=state.attemptName;if(state.attemptDate)$("attemptDate").value=state.attemptDate;if(state.revisionName){$("revisionName").textContent=state.revisionName;$("revisionDateLabel").textContent=state.revisionDate||"";$("revisionEmpty").classList.add("hidden");$("revisionView").classList.remove("hidden")}tick();setInterval(tick,60000);
